minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - eslint@10.8.1
  - '@tednaaa/eslint-config@0.1.1'

trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  esbuild: false
  lefthook: false
  vue-demi: false
